#   'PRD_DE': '202004',
#   'TBL_ID': 'DT_1B040A3',
#   'ITM_NM': '총인구수',
#   'ITM_NM_ENG': 'Koreans (Total)',
#   'ITM_ID': 'T20',
#   'UNIT_NM': '명',
#   'ORG_ID': '101',
#   'UNIT_NM_ENG': 'Person',
#   'C1_OBJ_NM': '행정구역(시군구)별',
#   'C1_OBJ_NM_ENG': 'By Administrative District',
#   'DT': '51842524',
#   'PRD_SE': 'M',
#   'C1': '00',
#   'C1_NM': '전국',
#   'C1_NM_ENG': 'Whole country'},
#  {'TBL_NM': '행정구역(시군구)별 성별 인구수',
#   'PRD_DE': '202004',
#   'TBL_ID': 'DT_1B040A3',
#   'ITM_NM': '총인구수',
#   'ITM_NM_ENG': 'Koreans (Total)',
#   'ITM_ID': 'T20',
#   'UNIT_NM': '명',
#   'ORG_ID': '101',
#   'UNIT_NM_ENG': 'Person',
#   'C1_OBJ_NM': '행정구역(시군구)별',
#   'C1_OBJ_NM_ENG': 'By Administrative District',
#   'DT': '9726787',
#   'PRD_SE': 'M',
#   'C1': '11',
#   'C1_NM': '서울특별시',
#   'C1_NM_ENG': 'Seoul'},
 
#  ...
 
#   {'TBL_NM': '행정구역(시군구)별 성별 인구수',
#   'PRD_DE': '202004',
#   'TBL_ID': 'DT_1B040A3',
#   'ITM_NM': '총인구수',
#   'ITM_NM_ENG': 'Koreans (Total)',
#   'ITM_ID': 'T20',
#   'UNIT_NM': '명',
#   'ORG_ID': '101',
#   'UNIT_NM_ENG': 'Person',
#   'C1_OBJ_NM': '행정구역(시군구)별',
#   'C1_OBJ_NM_ENG': 'By Administrative District',
#   'DT': '670595',
#   'PRD_SE': 'M',
#   'C1': '50',
#   'C1_NM': '제주특별자치도',
#   'C1_NM_ENG': 'Jeju-do'}]
